### ISSUE TITLE
Séance 2 : Architecture et Technos

### ISSUE THREAD

**Issue by Tdiouf10** [amran-zak/Petite-annonce#2]

**Comment by amran-zak** [comment]
![Architecture](https://user-images.githubusercontent.com/80887236/208091699-856b3f19-74dc-46c3-9eb0-392745bfd2ac.png)

**Comment by amran-zak** [comment]
![Architecture-1](https://user-images.githubusercontent.com/80887236/208091984-6873057f-a7bf-4685-bd63-ee5b79f83bd0.png)

**Comment by amran-zak** [comment]
![Architecture-2](https://user-images.githubusercontent.com/80887236/208092127-fecca1da-c407-441e-af10-8df1f2245c24.png)

**Comment by amran-zak** [comment]
![Architecture - final](https://user-images.githubusercontent.com/80887236/208123975-184016b8-db75-422d-8754-7b1a35c80cd4.png)
