### ISSUE TITLE
Séance 2 : Découpage, priorisation et répartition des tâches

### ISSUE THREAD

**Issue by Rinde17** [amran-zak/Petite-annonce#5]
Découpage du travail pour le projet & Répartition des tâches :

Full-stack : @amran-zak @mouaadlalaoui 
----------------------------------------------
Back-end : @Rinde17 @Tdiouf10 
------------------------------------
Front end : @perrineosw @NkwamoMaeva
-----------------------------------------------

**Comment by Tdiouf10** [comment]
Priorisation : 

1️⃣ Architecture et Technos
----------------------------
2️⃣ Modèle de données
----------------------------
3️⃣ Mockups
